// WARNING: This file was auto-generated by the Brawler Shader Compiler. You will incur the
// wrath of God if you dare touch it.

module;

export module Brawler.RootSignatures.RootSignatureID;

export namespace Brawler
{
	namespace RootSignatures
	{
		enum class RootSignatureID
		{
			TEST_ROOT_SIGNATURE,

			COUNT_OR_ERROR
		};
	}
}