// WARNING: This file was auto-generated by the Brawler Shader Compiler. You will incur the
// wrath of God if you dare touch it.

module;

export module Brawler.PSOs.PSODefinition:PSODefinitionBase;
import Brawler.PSOs.PSOID;

export namespace Brawler
{
	namespace PSOs
	{
		template <PSOID PSOIdentifier>
		struct PSODefinition
		{};
	}
}