// WARNING: This file was auto-generated by the Brawler Shader Compiler. You will incur the
// wrath of God if you dare touch it.

module;

export module Brawler.PSOs.PSOID;

export namespace Brawler
{
	namespace PSOs
	{
		enum class PSOID
		{
			BC7_TRY_MODE_456,
			BC7_TRY_MODE_137,
			BC7_TRY_MODE_02,
			BC7_ENCODE_BLOCK,
			GENERIC_DOWNSAMPLE,
			GENERIC_DOWNSAMPLE_SRGB,

			COUNT_OR_ERROR
		};
	}
}