// WARNING: This file was auto-generated by the Brawler Shader Compiler. You will incur the
// wrath of God if you dare touch it.

module;

export module Brawler.RootSignatures.RootSignatureID;

export namespace Brawler
{
	namespace RootSignatures
	{
		enum class RootSignatureID
		{
			BC6H_BC7_COMPRESSION,
			GENERIC_DOWNSAMPLE,
			VIRTUAL_TEXTURE_PAGE_TILING,
			VIRTUAL_TEXTURE_PAGE_MERGING,

			COUNT_OR_ERROR
		};
	}
}