// WARNING: This file was auto-generated by the Brawler Shader Compiler. You will incur the
// wrath of God if you dare touch it.

module;

export module Brawler.CommandSignatures.CommandSignatureID;

export namespace Brawler
{
	namespace CommandSignatures
	{
		enum class CommandSignatureID
		{
			DEFERRED_GEOMETRY_RASTER,

			COUNT_OR_ERROR
		};
	}
}