// WARNING: This file was auto-generated by the Brawler Shader Compiler. You will incur the
// wrath of God if you dare touch it.

module;

export module Brawler.CommandSignatures.CommandSignatureDefinition:CommandSignatureDefinitionBase;
import Brawler.CommandSignatures.CommandSignatureID;

export namespace Brawler
{
	namespace CommandSignatures
	{
		template <CommandSignatureID CSIdentifier>
		struct CommandSignatureDefinition
		{};
	}
}