// WARNING: This file was auto-generated by the Brawler Shader Compiler. You will incur the
// wrath of God if you dare touch it.

module;

export module Brawler.PSOs.PSOID;

export namespace Brawler
{
	namespace PSOs
	{
		enum class PSOID
		{
			DEFERRED_GEOMETRY_RASTER,
			MODEL_INSTANCE_FRUSTUM_CULL,
			DEFERRED_OPAQUE_SHADE,

			COUNT_OR_ERROR
		};
	}
}