// WARNING: This file was auto-generated by the Brawler Shader Compiler. You will incur the
// wrath of God if you dare touch it.

module;

export module Brawler.RootParameters.RootParameterEnums;
export import Brawler.D3D12.RootParameterType;

export namespace Brawler
{
	namespace RootParameters
	{
		enum class DeferredGeometryRaster
		{
			RASTER_CONSTANTS,
			BINDLESS_SRVS,

			COUNT_OR_ERROR
		};
	}
}