module;

export module Brawler.PSOID;

export namespace Brawler
{
	enum class PSOID
	{
		// Brawler Engine
		DEFERRED_GEOMETRY_RASTER,
		MODEL_INSTANCE_FRUSTUM_CULL,
		DEFERRED_OPAQUE_SHADE,

		// Brawler Model Exporter
		BC7_TRY_MODE_456,
		BC7_TRY_MODE_137,
		BC7_TRY_MODE_02,
		BC7_ENCODE_BLOCK,
		GENERIC_DOWNSAMPLE,
		GENERIC_DOWNSAMPLE_SRGB,
		VIRTUAL_TEXTURE_PAGE_TILING_POINT,
		VIRTUAL_TEXTURE_PAGE_TILING_BILINEAR,
		VIRTUAL_TEXTURE_PAGE_TILING_TRILINEAR,
		VIRTUAL_TEXTURE_PAGE_TILING_ANISOTROPIC,
		VIRTUAL_TEXTURE_PAGE_TILING_POINT_SRGB,
		VIRTUAL_TEXTURE_PAGE_TILING_BILINEAR_SRGB,
		VIRTUAL_TEXTURE_PAGE_TILING_TRILINEAR_SRGB,
		VIRTUAL_TEXTURE_PAGE_TILING_ANISOTROPIC_SRGB,
		VIRTUAL_TEXTURE_PAGE_MERGING_POINT,
		VIRTUAL_TEXTURE_PAGE_MERGING_BILINEAR,
		VIRTUAL_TEXTURE_PAGE_MERGING_TRILINEAR,
		VIRTUAL_TEXTURE_PAGE_MERGING_ANISOTROPIC,
		VIRTUAL_TEXTURE_PAGE_MERGING_POINT_SRGB,
		VIRTUAL_TEXTURE_PAGE_MERGING_BILINEAR_SRGB,
		VIRTUAL_TEXTURE_PAGE_MERGING_TRILINEAR_SRGB,
		VIRTUAL_TEXTURE_PAGE_MERGING_ANISOTROPIC_SRGB,

		// Test Shader Profile
		TEST_PSO,
		
		COUNT_OR_ERROR
	};
}