module;

export module Brawler.GPUSceneBufferID;

export namespace Brawler
{
	enum class GPUSceneBufferID
	{
		GLOBAL_VERTEX_BUFFER,
		MODEL_INSTANCE_TRANSFORM_DATA_BUFFER,
		VIEW_TRANSFORM_DATA_BUFFER,
		VIEW_DIMENSIONS_DATA_BUFFER,
		LIGHT_DESCRIPTOR_BUFFER,
		POINT_LIGHT_BUFFER,
		SPOTLIGHT_BUFFER,
		MODEL_INSTANCE_DESCRIPTOR_BUFFER,
		MATERIAL_DESCRIPTOR_BUFFER,

		COUNT_OR_ERROR
	};
}