module;

export module Brawler.GPUSceneBufferID;

export namespace Brawler
{
	enum class GPUSceneBufferID
	{
		GLOBAL_VERTEX_BUFFER,
		GLOBAL_INDEX_BUFFER,
		MODEL_INSTANCE_TRANSFORM_DATA_BUFFER,
		LOD_MESH_DATA_BUFFER,
		VIEW_TRANSFORM_DATA_BUFFER,
		VIEW_DIMENSIONS_DATA_BUFFER,
		GLOBAL_TRIANGLE_CLUSTER_BUFFER,
		LOD_MESH_DATA_INDEX_BUFFER,
		VIRTUAL_TEXTURE_DESCRIPTION_BUFFER,

		COUNT_OR_ERROR
	};
}